language: csharp
mono:
  - latest
os:
  - linux
  - osx
solution: KartRanking.sln
env:
  global:
    - ResolveNuGetPackageAssets=true
    - EnableNuGetPackageRestore=true
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore KartRanking.sln
script:
  - xbuild /p:Configuration=Release KartRanking.sln
cache:
  directories:
    - bin
