<?xml version="1.0" encoding="utf-8"?><Database Name="DataSource" Class="DataKartDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql.afonsoft.com.br;Initial Catalog=afonsoftcombr_db;Persist Security Info=True;User ID=afonsoftcombr;Connect Timeout=360;Load Balance Timeout=360" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="afonsoftcombr_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Usuarios" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Apelido" Type="System.String" DbType="NChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Senha" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Sexo" Type="System.Char" DbType="NChar(1)" CanBeNull="true" />
      <Column Name="Peso" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="DtNascimento" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MostarInfo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Altura" Type="System.Decimal" DbType="Decimal(3,2)" CanBeNull="true" />
      <Column Name="Telefone" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Celular" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="Foto" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Cidade" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="NChar(2)" CanBeNull="true" />
      <Column Name="Endereco" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Perfil_Facebook" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Perfil_Twitter" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Perfil_Plus" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Perfil_Outros" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Obs" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ativo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Usuario_Kart_Grid_Calendario" Member="Kart_Grid_Calendarios" ThisKey="idUsuario" OtherKey="idUsuario" Type="Kart_Grid_Calendario" />
      <Association Name="Usuario_Kart_Grupo" Member="Kart_Grupos" ThisKey="idUsuario" OtherKey="Id_Usuario_Lider" Type="Kart_Grupo" />
      <Association Name="Usuario_Kart_log_erro" Member="Kart_log_erros" ThisKey="idUsuario" OtherKey="idUsuario" Type="Kart_log_erro" />
      <Association Name="Usuario_Kart_Noticias_Grupo" Member="Kart_Noticias_Grupos" ThisKey="idUsuario" OtherKey="IdUsuario" Type="Kart_Noticias_Grupo" />
      <Association Name="Usuario_Kart_Resultado_Calendario" Member="Kart_Resultado_Calendarios" ThisKey="idUsuario" OtherKey="idUsuario" Type="Kart_Resultado_Calendario" />
      <Association Name="Usuario_Kart_Usuario_Equipe_Campeonato" Member="Kart_Usuario_Equipe_Campeonatos" ThisKey="idUsuario" OtherKey="idUsuario" Type="Kart_Usuario_Equipe_Campeonato" />
      <Association Name="Usuario_Kart_Usuario_Grupo" Member="Kart_Usuario_Grupos" ThisKey="idUsuario" OtherKey="idUsuario" Type="Kart_Usuario_Grupo" />
      <Association Name="Usuario_Kart_Album_Grupo" Member="Kart_Album_Grupos" ThisKey="idUsuario" OtherKey="IdUsuario" Type="Kart_Album_Grupo" />
      <Association Name="Usuario_Kart_Regras_Grupo" Member="Kart_Regras_Grupos" ThisKey="idUsuario" OtherKey="idUsuario" Type="Kart_Regras_Grupo" />
      <Association Name="Usuario_Kart_Videos_Grupo" Member="Kart_Videos_Grupos" ThisKey="idUsuario" OtherKey="idUsuario" Type="Kart_Videos_Grupo" />
      <Association Name="Usuario_Kart_Campeonato_Usuario_Desativado" Member="Kart_Campeonato_Usuario_Desativados" ThisKey="idUsuario" OtherKey="idUsuario" Type="Kart_Campeonato_Usuario_Desativado" />
      <Association Name="Usuario_Kart_log_acesso" Member="Kart_log_acessos" ThisKey="idUsuario" OtherKey="idUsuario" Type="Kart_log_acesso" />
    </Type>
  </Table>
  <Table Name="Kart_Calendario_Campeonato" Member="Kart_Calendario_Campeonatos">
    <Type Name="Kart_Calendario_Campeonato">
      <Column Name="idCalendario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.DateTime" DbType="SmallDateTime NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Kartodromo" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Horario" Type="System.String" DbType="NChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Circuito" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ativo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Kart_Calendario_Campeonato_Kart_Grid_Calendario" Member="Kart_Grid_Calendarios" ThisKey="idCalendario" OtherKey="idCalendario" Type="Kart_Grid_Calendario" />
      <Association Name="Kart_Calendario_Campeonato_Kart_Resultado_Calendario" Member="Kart_Resultado_Calendarios" ThisKey="idCalendario" OtherKey="idCalendario" Type="Kart_Resultado_Calendario" />
      <Association Name="Kart_Calendario_Campeonato_Kart_Videos_Grupo" Member="Kart_Videos_Grupos" ThisKey="idCalendario" OtherKey="idCalendario" Type="Kart_Videos_Grupo" />
      <Association Name="Kart_Campeonato_Kart_Calendario_Campeonato" Member="Kart_Campeonato" ThisKey="idCampeonato" OtherKey="idCampeonato" Type="Kart_Campeonato" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Campeonato" Member="Kart_Campeonatos">
    <Type Name="Kart_Campeonato">
      <Column Name="idCampeonato" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtInicio" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="dtFim" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NomeCampeonato" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ativo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Kart_Campeonato_Kart_Calendario_Campeonato" Member="Kart_Calendario_Campeonatos" ThisKey="idCampeonato" OtherKey="idCampeonato" Type="Kart_Calendario_Campeonato" />
      <Association Name="Kart_Campeonato_Kart_Equipe_Campeonato" Member="Kart_Equipe_Campeonatos" ThisKey="idCampeonato" OtherKey="idCampeonato" Type="Kart_Equipe_Campeonato" />
      <Association Name="Kart_Campeonato_Kart_Campeonato_Usuario_Desativado" Member="Kart_Campeonato_Usuario_Desativados" ThisKey="idCampeonato" OtherKey="idCampeonato" Type="Kart_Campeonato_Usuario_Desativado" />
      <Association Name="Kart_Campeonato_Kart_Equipe_Campeonato_Desativado" Member="Kart_Equipe_Campeonato_Desativados" ThisKey="idCampeonato" OtherKey="idCampeonato" Type="Kart_Equipe_Campeonato_Desativado" />
      <Association Name="Kart_Grupo_Kart_Campeonato" Member="Kart_Grupo" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Grupo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Equipe_Campeonato" Member="Kart_Equipe_Campeonatos">
    <Type Name="Kart_Equipe_Campeonato">
      <Column Name="idEquipeCampeonato" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NomeEquipe" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Sigla" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Kart_Equipe_Campeonato_Kart_Usuario_Equipe_Campeonato" Member="Kart_Usuario_Equipe_Campeonatos" ThisKey="idEquipeCampeonato" OtherKey="idEquipeCampeonato" Type="Kart_Usuario_Equipe_Campeonato" />
      <Association Name="Kart_Equipe_Campeonato_Kart_Equipe_Campeonato_Desativado" Member="Kart_Equipe_Campeonato_Desativados" ThisKey="idEquipeCampeonato" OtherKey="idEquipeCampeonato" Type="Kart_Equipe_Campeonato_Desativado" />
      <Association Name="Kart_Campeonato_Kart_Equipe_Campeonato" Member="Kart_Campeonato" ThisKey="idCampeonato" OtherKey="idCampeonato" Type="Kart_Campeonato" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Grid_Calendario" Member="Kart_Grid_Calendarios">
    <Type Name="Kart_Grid_Calendario">
      <Column Name="idGrid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCalendario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEquipe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Volta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tempoMinutos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tempoHoras" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tempoSegundos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tempoMilisegundos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtcriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Kart_Calendario_Campeonato_Kart_Grid_Calendario" Member="Kart_Calendario_Campeonato" ThisKey="idCalendario" OtherKey="idCalendario" Type="Kart_Calendario_Campeonato" IsForeignKey="true" />
      <Association Name="Usuario_Kart_Grid_Calendario" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Grupo" Member="Kart_Grupos">
    <Type Name="Kart_Grupo">
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NomeGrupo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Sigla" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id_Usuario_Lider" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="permitirInsricoes" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UrlAcesso" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cidade" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Estado" Type="System.String" DbType="NChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="Ativo" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Kart_Grupo_Kart_Campeonato" Member="Kart_Campeonatos" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Campeonato" />
      <Association Name="Kart_Grupo_Kart_Noticias_Grupo" Member="Kart_Noticias_Grupos" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Noticias_Grupo" />
      <Association Name="Kart_Grupo_Kart_Ponto_Grupo" Member="Kart_Ponto_Grupos" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Ponto_Grupo" />
      <Association Name="Kart_Grupo_Kart_Usuario_Grupo" Member="Kart_Usuario_Grupos" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Usuario_Grupo" />
      <Association Name="Kart_Grupo_Kart_Album_Grupo" Member="Kart_Album_Grupos" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Album_Grupo" />
      <Association Name="Kart_Grupo_Kart_Regras_Grupo" Member="Kart_Regras_Grupos" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Regras_Grupo" />
      <Association Name="Kart_Grupo_Kart_Videos_Grupo" Member="Kart_Videos_Grupos" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Videos_Grupo" />
      <Association Name="Usuario_Kart_Grupo" Member="Usuario" ThisKey="Id_Usuario_Lider" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_log_erro" Member="Kart_log_erros">
    <Type Name="Kart_log_erro">
      <Column Name="idErro" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserIP" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Column Name="URL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RawUrl" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="QueryString" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserAgent" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Referrer" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Mensagem" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Erro" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Keys" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StackTrace" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TargetSite" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Source" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Page" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dtErro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Usuario_Kart_log_erro" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Noticias_Grupo" Member="Kart_Noticias_Grupos">
    <Type Name="Kart_Noticias_Grupo">
      <Column Name="idNoticias" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Titulo" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Noticia" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Ativo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="dtEvento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kart_Grupo_Kart_Noticias_Grupo" Member="Kart_Grupo" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Grupo" IsForeignKey="true" />
      <Association Name="Usuario_Kart_Noticias_Grupo" Member="Usuario" ThisKey="IdUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Ponto_Grupo" Member="Kart_Ponto_Grupos">
    <Type Name="Kart_Ponto_Grupo">
      <Column Name="idPontoGrupo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ponto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="idUsuarioCadastro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kart_Grupo_Kart_Ponto_Grupo" Member="Kart_Grupo" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Grupo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Resultado_Calendario" Member="Kart_Resultado_Calendarios">
    <Type Name="Kart_Resultado_Calendario">
      <Column Name="idResultado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCalendario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idEquipe" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tempoHoras" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tempoMinutos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tempoSegundos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tempoMilisegundos" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ponto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Voltas" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Kart_Calendario_Campeonato_Kart_Resultado_Calendario" Member="Kart_Calendario_Campeonato" ThisKey="idCalendario" OtherKey="idCalendario" Type="Kart_Calendario_Campeonato" IsForeignKey="true" />
      <Association Name="Usuario_Kart_Resultado_Calendario" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Usuario_Equipe_Campeonato" Member="Kart_Usuario_Equipe_Campeonatos">
    <Type Name="Kart_Usuario_Equipe_Campeonato">
      <Column Name="idUsuarioEquipeCampeonato" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idEquipeCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Kart_Equipe_Campeonato_Kart_Usuario_Equipe_Campeonato" Member="Kart_Equipe_Campeonato" ThisKey="idEquipeCampeonato" OtherKey="idEquipeCampeonato" Type="Kart_Equipe_Campeonato" IsForeignKey="true" />
      <Association Name="Usuario_Kart_Usuario_Equipe_Campeonato" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Usuario_Grupo" Member="Kart_Usuario_Grupos">
    <Type Name="Kart_Usuario_Grupo">
      <Column Name="idGrupoUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Principal" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Aprovado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Kart_Grupo_Kart_Usuario_Grupo" Member="Kart_Grupo" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Grupo" IsForeignKey="true" />
      <Association Name="Usuario_Kart_Usuario_Grupo" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="View_Equipe_Usuario" Member="View_Equipe_Usuarios">
    <Type Name="View_Equipe_Usuario">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NomeEquipe" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Sigla" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="idEquipeCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="View_Kart_Usuario_Pontos_Grupo" Member="View_Kart_Usuario_Pontos_Grupos">
    <Type Name="View_Kart_Usuario_Pontos_Grupo">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Pontos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grupo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="View_Kart_Equipe_Pontos_Campeonato" Member="View_Kart_Equipe_Pontos_Campeonatos">
    <Type Name="View_Kart_Equipe_Pontos_Campeonato">
      <Column Name="idEquipeCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Equipe" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Sigla" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pontos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grupo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Campeonato" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="idCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="View_Kart_Usuario_Historico" Member="View_Kart_Usuario_Historicos">
    <Type Name="View_Kart_Usuario_Historico">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Pontos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Provas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Vitorias" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Podios" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="View_Kart_Usuario_Pontos_Campeonato" Member="View_Kart_Usuario_Pontos_Campeonatos">
    <Type Name="View_Kart_Usuario_Pontos_Campeonato">
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Nome" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Pontos" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Grupo" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Campeonato" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="idCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="Kart_Album_Grupo" Member="Kart_Album_Grupos">
    <Type Name="Kart_Album_Grupo">
      <Column Name="idAlbum" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NomeAlbum" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Descricao" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dtEvento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UrlFotos" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PathFotos" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Kart_Grupo_Kart_Album_Grupo" Member="Kart_Grupo" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Grupo" IsForeignKey="true" />
      <Association Name="Usuario_Kart_Album_Grupo" Member="Usuario" ThisKey="IdUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Regras_Grupo" Member="Kart_Regras_Grupos">
    <Type Name="Kart_Regras_Grupo">
      <Column Name="idRegra" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Regra" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtCadastro" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Ativo" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Kart_Grupo_Kart_Regras_Grupo" Member="Kart_Grupo" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Grupo" IsForeignKey="true" />
      <Association Name="Usuario_Kart_Regras_Grupo" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Videos_Grupo" Member="Kart_Videos_Grupos">
    <Type Name="Kart_Videos_Grupo">
      <Column Name="idVideo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idGrupo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCalendario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="txtTitulo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="dtEvento" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UrlVideo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="dtCriacao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Kart_Calendario_Campeonato_Kart_Videos_Grupo" Member="Kart_Calendario_Campeonato" ThisKey="idCalendario" OtherKey="idCalendario" Type="Kart_Calendario_Campeonato" IsForeignKey="true" />
      <Association Name="Kart_Grupo_Kart_Videos_Grupo" Member="Kart_Grupo" ThisKey="idGrupo" OtherKey="idGrupo" Type="Kart_Grupo" IsForeignKey="true" />
      <Association Name="Usuario_Kart_Videos_Grupo" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Campeonato_Usuario_Desativados" Member="Kart_Campeonato_Usuario_Desativados">
    <Type Name="Kart_Campeonato_Usuario_Desativado">
      <Column Name="idDesativado" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtCadastro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IdUsuarioCadastro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kart_Campeonato_Kart_Campeonato_Usuario_Desativado" Member="Kart_Campeonato" ThisKey="idCampeonato" OtherKey="idCampeonato" Type="Kart_Campeonato" IsForeignKey="true" />
      <Association Name="Usuario_Kart_Campeonato_Usuario_Desativado" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_Equipe_Campeonato_Desativados" Member="Kart_Equipe_Campeonato_Desativados">
    <Type Name="Kart_Equipe_Campeonato_Desativado">
      <Column Name="idDesativados" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idEquipeCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="idCampeonato" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtCadastro" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="idUsuarioCadastro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Kart_Campeonato_Kart_Equipe_Campeonato_Desativado" Member="Kart_Campeonato" ThisKey="idCampeonato" OtherKey="idCampeonato" Type="Kart_Campeonato" IsForeignKey="true" />
      <Association Name="Kart_Equipe_Campeonato_Kart_Equipe_Campeonato_Desativado" Member="Kart_Equipe_Campeonato" ThisKey="idEquipeCampeonato" OtherKey="idEquipeCampeonato" Type="Kart_Equipe_Campeonato" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Kart_log_acesso" Member="Kart_log_acessos">
    <Type Name="Kart_log_acesso">
      <Column Name="idAcesso" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dtAcesso" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Usuario_Kart_log_acesso" Member="Usuario" ThisKey="idUsuario" OtherKey="idUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="forumdb.phpbb_users" Member="phpbb_users">
    <Type Name="phpbb_user">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="group_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_permissions" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="user_perm_from" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_ip" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="user_regdate" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="username_clean" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="user_password" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="user_passchg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_pass_convert" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="user_email_hash" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="user_birthday" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="user_lastvisit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_lastmark" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_lastpost_time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_lastpage" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="user_last_confirm_key" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="user_last_search" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_warnings" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_last_warning" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_login_attempts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_inactive_reason" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_inactive_time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_posts" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_lang" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="user_timezone" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="user_dst" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_dateformat" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="user_style" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_rank" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_colour" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="user_new_privmsg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_unread_privmsg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_last_privmsg" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_message_rules" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_full_folder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_emailtime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_topic_show_days" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_topic_sortby_type" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="user_topic_sortby_dir" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="user_post_show_days" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_post_sortby_type" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="user_post_sortby_dir" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="user_notify" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_notify_pm" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_notify_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_allow_pm" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_allow_viewonline" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_allow_viewemail" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_allow_massemail" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_options" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_avatar" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="user_avatar_type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_avatar_width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_avatar_height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_sig" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="user_sig_bbcode_uid" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="user_sig_bbcode_bitfield" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="user_from" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="user_icq" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="user_aim" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="user_yim" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="user_msnm" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="user_jabber" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="user_website" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="user_occ" Type="System.String" DbType="VarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="user_interests" Type="System.String" DbType="VarChar(4000) NOT NULL" CanBeNull="false" />
      <Column Name="user_actkey" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="user_newpasswd" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="user_form_salt" Type="System.String" DbType="VarChar(32) NOT NULL" CanBeNull="false" />
      <Column Name="user_new" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_reminded" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_reminded_time" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="forumdb.phpbb_user_group" Member="phpbb_user_groups">
    <Type Name="phpbb_user_group">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="group_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="group_leader" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="user_pending" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>